---
version: '3'
services:
  tianlin-db:
    build: 
      context: .
      dockerfile: ./Dockerdb
    environment:
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
      # 导入的数据库sql文件(可binary)
      #SQL_FILE: chen.sql
    ports:
    - "3306:3306"
    - "33060:33060"
    volumes:
    - ./sh:/docker-entrypoint-initdb.d
    - ./sql:/tmp/sql
    restart: always
    
  tianlin-sb:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      # 对应以上数据库名
      DATABASE: chen
      # 对应以上数据库密码
      MYSQL_ROOT_PASSWORD: 123456
    links:
      - "tianlin-db:db"
    volumes:
      - ./src/:/tianlin/
    healthcheck:
      test: ["CMD","/bin/sh","-c","ps aux | grep ${JRE_NAME} | grep -v grep"]
      interval: 1m
      timeout: 5s
      retries: 1
      start_period: 60s
    restart: always
    container_name: tianlin-springboot
