---
version: '3'
services:
  tianlin-db:
    build: 
      context: .
      dockerfile: ./Dockerdb
    #image: mysql:latest
    environment:
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
      # 导入的数据库sql文件(可binary)
      #SQL_FILE: chen.sql
    ports:
    - "3306:3306"
    - "33060:33060"
    volumes:
    - ./sh:/docker-entrypoint-initdb.d
    - ./sql:/tmp/sql
    restart: always
    #command: /bin/bash -c cat /tmp/sql/*.sql | mysql -uroot -p${MYSQL_ROOT_PASSWORD} 2>&1 &>/dev/null || zcat /tmp/sql/*.sql | mysql -uroot -p${MYSQL_ROOT_PASSWORD} 2>&1 &>/dev/null ; mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "update mysql.user set plugin='mysql_native_password' where user='root' and host='%'"
    
  tianlin-sb:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      # 对应以上数据库名
      DATABASE: chen
      # 对应以上数据库密码
      MYSQL_ROOT_PASSWORD: 123456
    links:
      - "tianlin-db:db"
    volumes:
      - ./src/:/tianlin/
    #command: sed -ri "s@(spring.datasource.url=jdbc:mysql://).*(\?useSSL=.*)@\1db:3306/${DATABASE}\2@g" /tianlin/src/main/resources/application-jdbc.properties && sed -ri "s@(spring.datasource.password=).*@\1${MYSQL_ROOT_PASSWORD}@g" /tianlin/src/main/resources/application-jdbc.properties
    healthcheck:
      #test: ["CMD","netstat -tnlp | grep $(grep -i 'server.port' /tianlin/src/main/resources/application.properties | cut -d'=' -f2)"]
      test: ["CMD","/bin/sh","-c","ps aux | grep ${JRE_NAME} | grep -v grep"]
      interval: 1m
      timeout: 5s
      retries: 1
      start_period: 60s
    restart: always
    container_name: tianlin-springboot
